sudo: false
language: python
python: "3.7"
notifications:
  on_success: never
  on_failure: never
before_script:
- pip install tox

matrix:
  include:
  - env: TOXENV=djangolatest
    sudo: true
    dist: xenial
  allow_failures:
  - env: TOXENV=djangolatest

script: tox -e $TOXENV
